# Farmer Data

In [313]:
import pandas as pd
import numpy as np

In [314]:
locations = ['Garut', 'Indramayu', 'Karawang', 'Subang', 'Tasikmalaya']

In [315]:
columns = ['dmu',	'Land area (m2)',	'Land lease value (IDR)',	'Labor cost (IDR)',	'Seed purchase value (IDR)',	'Fertilizer purchase value (IDR)',	'Pesticide purchase value (IDR)',	'Equipment rent value (IDR)',	'Production value (IDR)']
farmer = pd.read_excel('dataset.xlsx', engine='openpyxl', sheet_name='Farmer Data', header=None)
farmer = farmer.iloc[:, :9]
farmer.dropna(subset=[0], inplace=True)
farmer

,0,1,2,3,4,5,6,7,8
0,Garut,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,dmu,Land area (m2),Land lease value (IDR),Labor cost (IDR),Seed purchase value (IDR),Fertilizer purchase value (IDR),Pesticide purchase value (IDR),Equipment rent value (IDR),Production value (IDR)
2,1,2800,4900000,1400000,644000,3640000,364000,470000,16200000
3,2,1400,4900000,500000,322000,1820000,182000,540000,8100000
4,3,2000,2000000,700000,200000,2600000,260000,690000,14850000
...,...,...,...,...,...,...,...,...,...
409,106,3500,6125000,2030000,805000,4550000,455000,500000,48150000
410,107,100,100000,97000,23000,130000,13000,250000,1620000
411,108,100,100000,90000,23000,130000,13000,350000,1620000
412,109,2800,4900000,1225000,644000,3640000,364000,430000,36450000
413,110,2800,4900000,500000,644000,3640000,364000,430000,36450000

In [316]:
farmer = farmer[~farmer[0].isin(locations)]
farmer

,0,1,2,3,4,5,6,7,8
1,dmu,Land area (m2),Land lease value (IDR),Labor cost (IDR),Seed purchase value (IDR),Fertilizer purchase value (IDR),Pesticide purchase value (IDR),Equipment rent value (IDR),Production value (IDR)
2,1,2800,4900000,1400000,644000,3640000,364000,470000,16200000
3,2,1400,4900000,500000,322000,1820000,182000,540000,8100000
4,3,2000,2000000,700000,200000,2600000,260000,690000,14850000
5,4,1000,1800000,800000,230000,1300000,100000,340000,13050000
...,...,...,...,...,...,...,...,...,...
409,106,3500,6125000,2030000,805000,4550000,455000,500000,48150000
410,107,100,100000,97000,23000,130000,13000,250000,1620000
411,108,100,100000,90000,23000,130000,13000,350000,1620000
412,109,2800,4900000,1225000,644000,3640000,364000,430000,36450000
413,110,2800,4900000,500000,644000,3640000,364000,430000,36450000

In [317]:
farmer.columns = columns
farmer

,dmu,Land area (m2),Land lease value (IDR),Labor cost (IDR),Seed purchase value (IDR),Fertilizer purchase value (IDR),Pesticide purchase value (IDR),Equipment rent value (IDR),Production value (IDR)
1,dmu,Land area (m2),Land lease value (IDR),Labor cost (IDR),Seed purchase value (IDR),Fertilizer purchase value (IDR),Pesticide purchase value (IDR),Equipment rent value (IDR),Production value (IDR)
2,1,2800,4900000,1400000,644000,3640000,364000,470000,16200000
3,2,1400,4900000,500000,322000,1820000,182000,540000,8100000
4,3,2000,2000000,700000,200000,2600000,260000,690000,14850000
5,4,1000,1800000,800000,230000,1300000,100000,340000,13050000
...,...,...,...,...,...,...,...,...,...
409,106,3500,6125000,2030000,805000,4550000,455000,500000,48150000
410,107,100,100000,97000,23000,130000,13000,250000,1620000
411,108,100,100000,90000,23000,130000,13000,350000,1620000
412,109,2800,4900000,1225000,644000,3640000,364000,430000,36450000
413,110,2800,4900000,500000,644000,3640000,364000,430000,36450000

In [318]:
farmer = farmer[farmer['dmu'] != 'dmu']
farmer

,dmu,Land area (m2),Land lease value (IDR),Labor cost (IDR),Seed purchase value (IDR),Fertilizer purchase value (IDR),Pesticide purchase value (IDR),Equipment rent value (IDR),Production value (IDR)
2,1,2800,4900000,1400000,644000,3640000,364000,470000,16200000
3,2,1400,4900000,500000,322000,1820000,182000,540000,8100000
4,3,2000,2000000,700000,200000,2600000,260000,690000,14850000
5,4,1000,1800000,800000,230000,1300000,100000,340000,13050000
6,5,800,1520000,580000,184000,1040000,104000,350000,10200000
...,...,...,...,...,...,...,...,...,...
409,106,3500,6125000,2030000,805000,4550000,455000,500000,48150000
410,107,100,100000,97000,23000,130000,13000,250000,1620000
411,108,100,100000,90000,23000,130000,13000,350000,1620000
412,109,2800,4900000,1225000,644000,3640000,364000,430000,36450000
413,110,2800,4900000,500000,644000,3640000,364000,430000,36450000

In [319]:
locations_val = locations
location_map = []
location_idx = 0
first_row = True

for idx, row in farmer.iterrows():
    if int(row['dmu']) == 1 and not first_row:
        location_idx += 1
    
    first_row = False
    
    if location_idx < len(locations_val):
        location_map.append(locations_val[location_idx])
    else:
        location_map.append(None)

farmer['Location'] = location_map
farmer

C:\Users\apits\AppData\Local\Temp\ipykernel_12900\433898568.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  farmer['Location'] = location_map

,dmu,Land area (m2),Land lease value (IDR),Labor cost (IDR),Seed purchase value (IDR),Fertilizer purchase value (IDR),Pesticide purchase value (IDR),Equipment rent value (IDR),Production value (IDR),Location
2,1,2800,4900000,1400000,644000,3640000,364000,470000,16200000,Garut
3,2,1400,4900000,500000,322000,1820000,182000,540000,8100000,Garut
4,3,2000,2000000,700000,200000,2600000,260000,690000,14850000,Garut
5,4,1000,1800000,800000,230000,1300000,100000,340000,13050000,Garut
6,5,800,1520000,580000,184000,1040000,104000,350000,10200000,Garut
...,...,...,...,...,...,...,...,...,...,...
409,106,3500,6125000,2030000,805000,4550000,455000,500000,48150000,Tasikmalaya
410,107,100,100000,97000,23000,130000,13000,250000,1620000,Tasikmalaya
411,108,100,100000,90000,23000,130000,13000,350000,1620000,Tasikmalaya
412,109,2800,4900000,1225000,644000,3640000,364000,430000,36450000,Tasikmalaya
413,110,2800,4900000,500000,644000,3640000,364000,430000,36450000,Tasikmalaya

In [320]:
farmer['dmu'] = farmer['dmu'].astype(np.int64)

for col in farmer.columns[1:9]:
    farmer[col] = farmer[col].astype(np.float64)
farmer

C:\Users\apits\AppData\Local\Temp\ipykernel_12900\2346175449.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  farmer['dmu'] = farmer['dmu'].astype(np.int64)
C:\Users\apits\AppData\Local\Temp\ipykernel_12900\2346175449.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  farmer[col] = farmer[col].astype(np.float64)
C:\Users\apits\AppData\Local\Temp\ipykernel_12900\2346175449.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  farmer[col] = farmer[col].astype(np.float64)
C:\Users\apits\AppData\Local\Temp\ipykernel_12900\2346175449.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  farmer[col] = farmer[col].astype(np.float64)
C:\Users\apits\AppData\Local\Temp\ipykernel_12900\2346175449.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  farmer[col] = farmer[col].astype(np.float64)
C:\Users\apits\AppData\Local\Temp\ipykernel_12900\2346175449.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  farmer[col] = farmer[col].astype(np.float64)
C:\Users\apits\AppData\Local\Temp\ipykernel_12900\2346175449.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  farmer[col] = farmer[col].astype(np.float64)
C:\Users\apits\AppData\Local\Temp\ipykernel_12900\2346175449.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  farmer[col] = farmer[col].astype(np.float64)
C:\Users\apits\AppData\Local\Temp\ipykernel_12900\2346175449.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  farmer[col] = farmer[col].astype(np.float64)

,dmu,Land area (m2),Land lease value (IDR),Labor cost (IDR),Seed purchase value (IDR),Fertilizer purchase value (IDR),Pesticide purchase value (IDR),Equipment rent value (IDR),Production value (IDR),Location
2,1,2800.0,4900000.0,1400000.0,644000.0,3640000.0,364000.0,470000.0,16200000.0,Garut
3,2,1400.0,4900000.0,500000.0,322000.0,1820000.0,182000.0,540000.0,8100000.0,Garut
4,3,2000.0,2000000.0,700000.0,200000.0,2600000.0,260000.0,690000.0,14850000.0,Garut
5,4,1000.0,1800000.0,800000.0,230000.0,1300000.0,100000.0,340000.0,13050000.0,Garut
6,5,800.0,1520000.0,580000.0,184000.0,1040000.0,104000.0,350000.0,10200000.0,Garut
...,...,...,...,...,...,...,...,...,...,...
409,106,3500.0,6125000.0,2030000.0,805000.0,4550000.0,455000.0,500000.0,48150000.0,Tasikmalaya
410,107,100.0,100000.0,97000.0,23000.0,130000.0,13000.0,250000.0,1620000.0,Tasikmalaya
411,108,100.0,100000.0,90000.0,23000.0,130000.0,13000.0,350000.0,1620000.0,Tasikmalaya
412,109,2800.0,4900000.0,1225000.0,644000.0,3640000.0,364000.0,430000.0,36450000.0,Tasikmalaya
413,110,2800.0,4900000.0,500000.0,644000.0,3640000.0,364000.0,430000.0,36450000.0,Tasikmalaya

In [321]:
farmer.info()

<class 'pandas.core.frame.DataFrame'>
Index: 400 entries, 2 to 413
Data columns (total 10 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   dmu                              400 non-null    int64
 1   Land area (m2)                   400 non-null    float64
 2   Land lease value (IDR)           400 non-null    float64
 3   Labor cost (IDR)                 400 non-null    float64
 4   Seed purchase value (IDR)        400 non-null    float64
 5   Fertilizer purchase value (IDR)  400 non-null    float64
 6   Pesticide purchase value (IDR)   400 non-null    float64
 7   Equipment rent value (IDR)       400 non-null    float64
 8   Production value (IDR)           400 non-null    float64
 9   Location                         400 non-null    object
dtypes: float64(8), int64(1), object(1)
memory usage: 34.4+ KB

In [322]:
for loc in locations:
  print(loc)
  display(farmer[farmer.Location == loc].describe())

Garut

,dmu,Land area (m2),Land lease value (IDR),Labor cost (IDR),Seed purchase value (IDR),Fertilizer purchase value (IDR),Pesticide purchase value (IDR),Equipment rent value (IDR),Production value (IDR)
count,98.000000,98.000000,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01
mean,49.500000,1996.734694,3.985046e+06,9.316327e+05,4.620959e+05,2.613020e+06,2.541173e+05,6.105663e+05,1.874601e+07
std,28.434134,1790.579458,4.423385e+06,1.328335e+06,4.099138e+05,2.340813e+06,2.318329e+05,5.514220e+05,2.157334e+07
min,1.000000,120.000000,2.100000e+05,7.000000e+04,2.760000e+04,1.560000e+05,1.560000e+04,2.400000e+05,1.740000e+06
25%,25.250000,1012.500000,1.268750e+06,5.000000e+05,2.760000e+05,1.316250e+06,1.387750e+05,3.500000e+05,9.300000e+06
50%,49.500000,1400.000000,3.237500e+06,6.600000e+05,3.220000e+05,1.820000e+06,1.820000e+05,4.262500e+05,1.357000e+07
75%,73.750000,2100.000000,4.900000e+06,9.600000e+05,4.830000e+05,2.730000e+06,2.730000e+05,6.400000e+05,2.456250e+07
max,98.000000,15000.000000,2.625000e+07,1.300000e+07,3.450000e+06,1.950000e+07,1.950000e+06,3.790000e+06,1.980000e+08

Indramayu

,dmu,Land area (m2),Land lease value (IDR),Labor cost (IDR),Seed purchase value (IDR),Fertilizer purchase value (IDR),Pesticide purchase value (IDR),Equipment rent value (IDR),Production value (IDR)
count,62.000000,62.000000,6.200000e+01,6.200000e+01,6.200000e+01,6.200000e+01,6.200000e+01,6.200000e+01,6.200000e+01
mean,31.500000,5718.112903,1.375696e+07,3.493065e+06,1.278561e+06,7.411289e+06,9.230644e+05,1.650653e+06,5.574806e+07
std,18.041619,4649.553139,1.099759e+07,3.476822e+06,1.006572e+06,5.955849e+06,7.729686e+05,9.010790e+05,4.234874e+07
min,1.000000,140.000000,2.450000e+05,1.000000e+05,3.220000e+04,1.820000e+05,1.820000e+04,4.900000e+05,1.860000e+06
25%,16.250000,2000.000000,3.500000e+06,7.750000e+05,4.600000e+05,2.600000e+06,2.600000e+05,1.090000e+06,2.565000e+07
50%,31.500000,5000.000000,1.260000e+07,3.000000e+06,1.150000e+06,6.500000e+06,8.645000e+05,1.317500e+06,4.765000e+07
75%,46.750000,8300.000000,1.791000e+07,5.000000e+06,1.840000e+06,1.040000e+07,1.300000e+06,2.190000e+06,7.924750e+07
max,62.000000,20000.000000,4.500000e+07,1.420000e+07,4.600000e+06,2.600000e+07,2.940000e+06,5.590000e+06,1.863000e+08

Karawang

,dmu,Land area (m2),Land lease value (IDR),Labor cost (IDR),Seed purchase value (IDR),Fertilizer purchase value (IDR),Pesticide purchase value (IDR),Equipment rent value (IDR),Production value (IDR)
count,53.000000,53.000000,5.300000e+01,5.300000e+01,5.300000e+01,5.300000e+01,5.300000e+01,5.300000e+01,5.300000e+01
mean,27.000000,13575.471698,2.348491e+07,5.487925e+06,3.126132e+06,1.764811e+07,2.149906e+06,2.326604e+06,1.090048e+08
std,15.443445,7302.789395,3.805404e+07,5.781563e+06,1.683246e+06,9.493626e+06,1.272732e+06,1.252917e+06,6.725020e+07
min,1.000000,2500.000000,8.750000e+06,7.200000e+05,5.750000e+05,3.250000e+06,3.250000e+05,6.900000e+05,1.280000e+07
25%,14.000000,10000.000000,1.200000e+07,2.400000e+06,2.300000e+06,1.300000e+07,1.200000e+06,1.380000e+06,6.240000e+07
50%,27.000000,10000.000000,1.440000e+07,3.600000e+06,2.300000e+06,1.300000e+07,1.500000e+06,2.000000e+06,8.160000e+07
75%,40.000000,20000.000000,1.800000e+07,5.000000e+06,4.600000e+06,2.600000e+07,3.000000e+06,2.700000e+06,1.485000e+08
max,53.000000,30000.000000,2.550000e+08,3.200000e+07,6.900000e+06,3.900000e+07,5.040000e+06,5.600000e+06,2.673000e+08

Subang

,dmu,Land area (m2),Land lease value (IDR),Labor cost (IDR),Seed purchase value (IDR),Fertilizer purchase value (IDR),Pesticide purchase value (IDR),Equipment rent value (IDR),Production value (IDR)
count,77.000000,77.000000,7.700000e+01,7.700000e+01,7.700000e+01,7.700000e+01,7.700000e+01,7.700000e+01,7.700000e+01
mean,39.000000,4318.441558,9.890532e+06,3.141039e+06,9.180763e+05,5.628649e+06,6.395208e+05,1.477546e+06,4.201941e+07
std,22.371857,3784.633426,1.057039e+07,3.629975e+06,8.815068e+05,4.891528e+06,6.981970e+05,1.935443e+06,4.254390e+07
min,1.000000,700.000000,9.800000e+05,3.000000e+05,1.002772e+05,9.100000e+05,9.100000e+04,2.720000e+05,5.400000e+06
25%,20.000000,1650.000000,3.150000e+06,5.000000e+05,3.450000e+05,2.145000e+06,2.210000e+05,4.700000e+05,1.515000e+07
50%,39.000000,2700.000000,5.400000e+06,1.000000e+06,5.600000e+05,3.510000e+06,3.640000e+05,6.900000e+05,2.565000e+07
75%,58.000000,5600.000000,1.305000e+07,6.000000e+06,1.150000e+06,7.280000e+06,9.100000e+05,1.200000e+06,5.130000e+07
max,77.000000,20000.000000,5.000000e+07,1.500000e+07,4.600000e+06,2.600000e+07,4.350000e+06,7.500009e+06,2.673000e+08

Tasikmalaya

,dmu,Land area (m2),Land lease value (IDR),Labor cost (IDR),Seed purchase value (IDR),Fertilizer purchase value (IDR),Pesticide purchase value (IDR),Equipment rent value (IDR),Production value (IDR)
count,110.000000,110.000000,1.100000e+02,1.100000e+02,1.100000e+02,1.100000e+02,1.100000e+02,1.100000e+02,1.100000e+02
mean,55.500000,1906.200000,2.872261e+06,1.309159e+06,4.328260e+05,2.472333e+06,2.478060e+05,4.804127e+05,2.020445e+07
std,31.898276,1584.642742,2.737601e+06,1.472169e+06,3.351230e+05,2.060204e+06,2.060036e+05,2.760612e+05,1.884862e+07
min,1.000000,100.000000,1.000000e+05,5.500000e+04,2.300000e+04,1.300000e+05,1.300000e+04,1.270000e+05,1.620000e+06
25%,28.250000,910.000000,1.386000e+06,4.906250e+05,2.101050e+05,1.183000e+06,1.183000e+05,3.115000e+05,7.210500e+06
50%,55.500000,1610.000000,2.100000e+06,5.000000e+05,3.703000e+05,2.051000e+06,2.093000e+05,3.870000e+05,1.414500e+07
75%,82.750000,2800.000000,3.675000e+06,1.975000e+06,6.440000e+05,3.640000e+06,3.640000e+05,5.522500e+05,2.790000e+07
max,110.000000,10000.000000,1.800000e+07,8.400000e+06,1.610000e+06,1.300000e+07,1.300000e+06,1.700000e+06,9.405000e+07

In [323]:
farmer

,dmu,Land area (m2),Land lease value (IDR),Labor cost (IDR),Seed purchase value (IDR),Fertilizer purchase value (IDR),Pesticide purchase value (IDR),Equipment rent value (IDR),Production value (IDR),Location
2,1,2800.0,4900000.0,1400000.0,644000.0,3640000.0,364000.0,470000.0,16200000.0,Garut
3,2,1400.0,4900000.0,500000.0,322000.0,1820000.0,182000.0,540000.0,8100000.0,Garut
4,3,2000.0,2000000.0,700000.0,200000.0,2600000.0,260000.0,690000.0,14850000.0,Garut
5,4,1000.0,1800000.0,800000.0,230000.0,1300000.0,100000.0,340000.0,13050000.0,Garut
6,5,800.0,1520000.0,580000.0,184000.0,1040000.0,104000.0,350000.0,10200000.0,Garut
...,...,...,...,...,...,...,...,...,...,...
409,106,3500.0,6125000.0,2030000.0,805000.0,4550000.0,455000.0,500000.0,48150000.0,Tasikmalaya
410,107,100.0,100000.0,97000.0,23000.0,130000.0,13000.0,250000.0,1620000.0,Tasikmalaya
411,108,100.0,100000.0,90000.0,23000.0,130000.0,13000.0,350000.0,1620000.0,Tasikmalaya
412,109,2800.0,4900000.0,1225000.0,644000.0,3640000.0,364000.0,430000.0,36450000.0,Tasikmalaya
413,110,2800.0,4900000.0,500000.0,644000.0,3640000.0,364000.0,430000.0,36450000.0,Tasikmalaya

# Rice Miller

In [324]:
rice_miller = pd.read_excel('dataset.xlsx', engine='openpyxl', sheet_name='Rice Miller Data', header=None)
rice_miller.dropna(subset=[0], inplace=True)
rice_miller

,0,1,2,3,4,5,6,7
0,Garut,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,dmu,Number of machines (unit),Value of milled grains (IDR),Amount of milled rice (Kg),Labor cost (IDR),Supporting equipment cost (IDR),nilaiberashasilgiling,Total revenue of milling machine (IDR)
2,1,4,331000000.0,40000,8987594.966762,1599538.461538,387053194.51556,37440000
3,2,5,315000000,42000,7190075.973409,1599538.461538,420000000,35000000
4,3,2,240000000,36000,2000000,3000000,360000000,30000000
...,...,...,...,...,...,...,...,...
114,25,1,9000000,1000,8950146.6544,1599538.461538,9000000,1040000
115,26,1,8100000.0,1300,2500000,500000,12579228.821756,884000
116,27,1,8550000,700,1797518.993352,250000,6440000,780000
117,28,1,7500000,800,8950146.6544,300000,8640000,780000
118,29,1,3000000,300,2000000,300000,2902898.958867,312000

In [325]:
rice_miller.columns = rice_miller.iloc[1].values
rice_miller

,dmu,Number of machines (unit),Value of milled grains (IDR),Amount of milled rice (Kg),Labor cost (IDR),Supporting equipment cost (IDR),nilaiberashasilgiling,Total revenue of milling machine (IDR)
0,Garut,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,dmu,Number of machines (unit),Value of milled grains (IDR),Amount of milled rice (Kg),Labor cost (IDR),Supporting equipment cost (IDR),nilaiberashasilgiling,Total revenue of milling machine (IDR)
2,1,4,331000000.0,40000,8987594.966762,1599538.461538,387053194.51556,37440000
3,2,5,315000000,42000,7190075.973409,1599538.461538,420000000,35000000
4,3,2,240000000,36000,2000000,3000000,360000000,30000000
...,...,...,...,...,...,...,...,...
114,25,1,9000000,1000,8950146.6544,1599538.461538,9000000,1040000
115,26,1,8100000.0,1300,2500000,500000,12579228.821756,884000
116,27,1,8550000,700,1797518.993352,250000,6440000,780000
117,28,1,7500000,800,8950146.6544,300000,8640000,780000
118,29,1,3000000,300,2000000,300000,2902898.958867,312000

In [326]:
rice_miller = rice_miller[~rice_miller['dmu'].isin(locations)]
rice_miller = rice_miller[rice_miller['dmu'] != 'dmu']
rice_miller

,dmu,Number of machines (unit),Value of milled grains (IDR),Amount of milled rice (Kg),Labor cost (IDR),Supporting equipment cost (IDR),nilaiberashasilgiling,Total revenue of milling machine (IDR)
2,1,4,331000000.0,40000,8987594.966762,1599538.461538,387053194.51556,37440000
3,2,5,315000000,42000,7190075.973409,1599538.461538,420000000,35000000
4,3,2,240000000,36000,2000000,3000000,360000000,30000000
5,4,2,270000000,36000,4500000,6000000,360000000,30000000
6,5,1,300000000,38412,8950146.6544,1599538.461538,384120000,31200000
...,...,...,...,...,...,...,...,...
114,25,1,9000000,1000,8950146.6544,1599538.461538,9000000,1040000
115,26,1,8100000.0,1300,2500000,500000,12579228.821756,884000
116,27,1,8550000,700,1797518.993352,250000,6440000,780000
117,28,1,7500000,800,8950146.6544,300000,8640000,780000
118,29,1,3000000,300,2000000,300000,2902898.958867,312000

In [327]:
rice_miller.isnull().sum()

dmu                                       0
Number of machines (unit)                 0
Value of milled grains (IDR)              0
Amount of milled rice (Kg)                0
Labor cost (IDR)                          0
Supporting equipment cost (IDR)           0
nilaiberashasilgiling                     0
Total revenue of milling machine (IDR)    0
dtype: int64

In [328]:
locations_val = locations
location_map = []
location_idx = 0
first_row = True

for idx, row in rice_miller.iterrows():
    if int(row['dmu']) == 1 and not first_row:
        location_idx += 1
    
    first_row = False
    
    if location_idx < len(locations_val):
        location_map.append(locations_val[location_idx])
    else:
        location_map.append(None)

rice_miller['Location'] = location_map
rice_miller

,dmu,Number of machines (unit),Value of milled grains (IDR),Amount of milled rice (Kg),Labor cost (IDR),Supporting equipment cost (IDR),nilaiberashasilgiling,Total revenue of milling machine (IDR),Location
2,1,4,331000000.0,40000,8987594.966762,1599538.461538,387053194.51556,37440000,Garut
3,2,5,315000000,42000,7190075.973409,1599538.461538,420000000,35000000,Garut
4,3,2,240000000,36000,2000000,3000000,360000000,30000000,Garut
5,4,2,270000000,36000,4500000,6000000,360000000,30000000,Garut
6,5,1,300000000,38412,8950146.6544,1599538.461538,384120000,31200000,Garut
...,...,...,...,...,...,...,...,...,...
114,25,1,9000000,1000,8950146.6544,1599538.461538,9000000,1040000,Tasikmalaya
115,26,1,8100000.0,1300,2500000,500000,12579228.821756,884000,Tasikmalaya
116,27,1,8550000,700,1797518.993352,250000,6440000,780000,Tasikmalaya
117,28,1,7500000,800,8950146.6544,300000,8640000,780000,Tasikmalaya
118,29,1,3000000,300,2000000,300000,2902898.958867,312000,Tasikmalaya

In [329]:
rice_miller['dmu'] = rice_miller['dmu'].astype(np.int64)
for col in rice_miller.columns[1:8]:
    rice_miller[col] = rice_miller[col].astype(np.float64)
rice_miller

,dmu,Number of machines (unit),Value of milled grains (IDR),Amount of milled rice (Kg),Labor cost (IDR),Supporting equipment cost (IDR),nilaiberashasilgiling,Total revenue of milling machine (IDR),Location
2,1,4.0,331000000.0,40000.0,8.987595e+06,1.599538e+06,3.870532e+08,37440000.0,Garut
3,2,5.0,315000000.0,42000.0,7.190076e+06,1.599538e+06,4.200000e+08,35000000.0,Garut
4,3,2.0,240000000.0,36000.0,2.000000e+06,3.000000e+06,3.600000e+08,30000000.0,Garut
5,4,2.0,270000000.0,36000.0,4.500000e+06,6.000000e+06,3.600000e+08,30000000.0,Garut
6,5,1.0,300000000.0,38412.0,8.950147e+06,1.599538e+06,3.841200e+08,31200000.0,Garut
...,...,...,...,...,...,...,...,...,...
114,25,1.0,9000000.0,1000.0,8.950147e+06,1.599538e+06,9.000000e+06,1040000.0,Tasikmalaya
115,26,1.0,8100000.0,1300.0,2.500000e+06,5.000000e+05,1.257923e+07,884000.0,Tasikmalaya
116,27,1.0,8550000.0,700.0,1.797519e+06,2.500000e+05,6.440000e+06,780000.0,Tasikmalaya
117,28,1.0,7500000.0,800.0,8.950147e+06,3.000000e+05,8.640000e+06,780000.0,Tasikmalaya
118,29,1.0,3000000.0,300.0,2.000000e+06,3.000000e+05,2.902899e+06,312000.0,Tasikmalaya

In [330]:
rice_miller.info()

<class 'pandas.core.frame.DataFrame'>
Index: 105 entries, 2 to 118
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   dmu                                     105 non-null    int64
 1   Number of machines (unit)               105 non-null    float64
 2   Value of milled grains (IDR)            105 non-null    float64
 3   Amount of milled rice (Kg)              105 non-null    float64
 4   Labor cost (IDR)                        105 non-null    float64
 5   Supporting equipment cost (IDR)         105 non-null    float64
 6   nilaiberashasilgiling                   105 non-null    float64
 7   Total revenue of milling machine (IDR)  105 non-null    float64
 8   Location                                105 non-null    object
dtypes: float64(7), int64(1), object(1)
memory usage: 8.2+ KB

In [331]:
for loc in locations:
  print(loc)
  display(rice_miller[rice_miller.Location == loc].tail())

Garut

,dmu,Number of machines (unit),Value of milled grains (IDR),Amount of milled rice (Kg),Labor cost (IDR),Supporting equipment cost (IDR),nilaiberashasilgiling,Total revenue of milling machine (IDR),Location
21,20,1.0,16500000.0,2100.0,8.950147e+06,800000.0,21000000.0,1560000.0,Garut
22,21,1.0,5000000.0,600.0,3.595038e+06,150000.0,5400000.0,520000.0,Garut
23,22,1.0,5000000.0,600.0,3.595038e+06,150000.0,5400000.0,520000.0,Garut
24,23,1.0,5000000.0,600.0,3.595038e+06,150000.0,5400000.0,520000.0,Garut
25,24,1.0,5000000.0,500.0,3.595038e+06,150000.0,5000000.0,520000.0,Garut

Indramayu

,dmu,Number of machines (unit),Value of milled grains (IDR),Amount of milled rice (Kg),Labor cost (IDR),Supporting equipment cost (IDR),nilaiberashasilgiling,Total revenue of milling machine (IDR),Location
41,13,4.0,330000000.0,38412.0,4.000000e+07,1.599538e+06,3.457080e+08,31200000.0,Indramayu
42,14,4.0,150000000.0,18000.0,1.797519e+07,1.599538e+06,1.741739e+08,15600000.0,Indramayu
43,15,4.0,75000000.0,9000.0,1.000000e+07,5.000000e+06,8.708697e+07,7800000.0,Indramayu
44,16,3.0,20000000.0,3000.0,1.200000e+07,5.000000e+06,2.902899e+07,2080000.0,Indramayu
45,17,2.0,20000000.0,2500.0,4.000000e+06,3.200000e+06,2.250000e+07,2080000.0,Indramayu

Karawang

,dmu,Number of machines (unit),Value of milled grains (IDR),Amount of milled rice (Kg),Labor cost (IDR),Supporting equipment cost (IDR),nilaiberashasilgiling,Total revenue of milling machine (IDR),Location
58,10,2.0,55000000.0,6000.0,8.987595e+06,4.000000e+06,5.800000e+07,5200000.0,Karawang
59,11,2.0,53000000.0,5000.0,7.190076e+06,1.599538e+06,5.000000e+07,5200000.0,Karawang
60,12,2.0,50000000.0,5000.0,7.190076e+06,1.000000e+06,4.750000e+07,5200000.0,Karawang
61,13,2.0,25000000.0,2500.0,8.950147e+06,1.500000e+06,2.419082e+07,2600000.0,Karawang
62,14,2.0,4800000.0,500.0,8.987595e+06,3.000000e+06,4.500000e+06,520000.0,Karawang

Subang

,dmu,Number of machines (unit),Value of milled grains (IDR),Amount of milled rice (Kg),Labor cost (IDR),Supporting equipment cost (IDR),nilaiberashasilgiling,Total revenue of milling machine (IDR),Location
82,17,2.0,165000000.0,18900.0,7.190076e+06,500000.0,1.512000e+08,4000000.0,Subang
83,18,3.0,110000000.0,15750.0,7.190076e+06,500000.0,1.260000e+08,13000000.0,Subang
84,19,1.0,100000000.0,10000.0,1.438015e+07,500000.0,9.676330e+07,10400000.0,Subang
85,20,4.0,100000000.0,10000.0,1.438015e+07,500000.0,9.676330e+07,6000000.0,Subang
86,21,3.0,100800000.0,10000.0,2.157023e+07,4000000.0,9.400000e+07,12000000.0,Subang

Tasikmalaya

,dmu,Number of machines (unit),Value of milled grains (IDR),Amount of milled rice (Kg),Labor cost (IDR),Supporting equipment cost (IDR),nilaiberashasilgiling,Total revenue of milling machine (IDR),Location
114,25,1.0,9000000.0,1000.0,8.950147e+06,1.599538e+06,9.000000e+06,1040000.0,Tasikmalaya
115,26,1.0,8100000.0,1300.0,2.500000e+06,5.000000e+05,1.257923e+07,884000.0,Tasikmalaya
116,27,1.0,8550000.0,700.0,1.797519e+06,2.500000e+05,6.440000e+06,780000.0,Tasikmalaya
117,28,1.0,7500000.0,800.0,8.950147e+06,3.000000e+05,8.640000e+06,780000.0,Tasikmalaya
118,29,1.0,3000000.0,300.0,2.000000e+06,3.000000e+05,2.902899e+06,312000.0,Tasikmalaya

# Middlemen

In [332]:
middlemen = pd.read_excel('dataset.xlsx', engine='openpyxl', sheet_name='Middlemen Data', header=None)
middlemen.dropna(subset=[0], inplace=True)
middlemen

,0,1,2,3,4,5,6,7,8
0,Garut,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,dmu,Total rice purchase (kg),Total rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Total precipitation (%),Precipitation quality (%)
2,1,700,6300000,1000000,500000,300000,6300000,5,5
3,2,700,6300000,1000000,1000000,300000,6300000,5,5
4,3,1000,10000000,3200000,5035346.798252,1200000,7040000,5,5
...,...,...,...,...,...,...,...,...,...
113,25,10000,83000000,1000000,1007069.35965,600000,88000000,20,15
114,26,10000,83000000,1000000,5000000,1000000,88000000,40,40
115,27,10000,83000000,2000000,1100000,280000,88000000,12,15
116,28,10000,83000000,2000000,2400000,200000,98000000,10,13
117,29,40000,332001481.481482,3200000,6000000,6500000,350240000,45,30

In [333]:
middlemen.columns = middlemen.iloc[1].values
middlemen = middlemen[~middlemen['dmu'].isin(locations)]
middlemen = middlemen[middlemen['dmu'] != 'dmu']
middlemen

,dmu,Total rice purchase (kg),Total rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Total precipitation (%),Precipitation quality (%)
2,1,700,6300000,1000000,500000,300000,6300000,5,5
3,2,700,6300000,1000000,1000000,300000,6300000,5,5
4,3,1000,10000000,3200000,5035346.798252,1200000,7040000,5,5
5,4,900,9000000,1100000,6400000,180000,7920000,20,10
6,5,900,7470000,1500000,2400000,300000,8100000,5,5
...,...,...,...,...,...,...,...,...,...
113,25,10000,83000000,1000000,1007069.35965,600000,88000000,20,15
114,26,10000,83000000,1000000,5000000,1000000,88000000,40,40
115,27,10000,83000000,2000000,1100000,280000,88000000,12,15
116,28,10000,83000000,2000000,2400000,200000,98000000,10,13
117,29,40000,332001481.481482,3200000,6000000,6500000,350240000,45,30

In [334]:
locations_val = locations
location_map = []
location_idx = 0
first_row = True

for idx, row in middlemen.iterrows():
    if int(row['dmu']) == 1 and not first_row:
        location_idx += 1
    
    first_row = False
    
    if location_idx < len(locations_val):
        location_map.append(locations_val[location_idx])
    else:
        location_map.append(None)

middlemen['Location'] = location_map
middlemen

,dmu,Total rice purchase (kg),Total rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Total precipitation (%),Precipitation quality (%),Location
2,1,700,6300000,1000000,500000,300000,6300000,5,5,Garut
3,2,700,6300000,1000000,1000000,300000,6300000,5,5,Garut
4,3,1000,10000000,3200000,5035346.798252,1200000,7040000,5,5,Garut
5,4,900,9000000,1100000,6400000,180000,7920000,20,10,Garut
6,5,900,7470000,1500000,2400000,300000,8100000,5,5,Garut
...,...,...,...,...,...,...,...,...,...,...
113,25,10000,83000000,1000000,1007069.35965,600000,88000000,20,15,Tasikmalaya
114,26,10000,83000000,1000000,5000000,1000000,88000000,40,40,Tasikmalaya
115,27,10000,83000000,2000000,1100000,280000,88000000,12,15,Tasikmalaya
116,28,10000,83000000,2000000,2400000,200000,98000000,10,13,Tasikmalaya
117,29,40000,332001481.481482,3200000,6000000,6500000,350240000,45,30,Tasikmalaya

In [335]:
middlemen['dmu'] = middlemen['dmu'].astype(np.int64)
for col in middlemen.columns[1:8]:
    middlemen[col] = middlemen[col].astype(np.float64)
middlemen

,dmu,Total rice purchase (kg),Total rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Total precipitation (%),Precipitation quality (%),Location
2,1,700.0,6.300000e+06,1000000.0,5.000000e+05,300000.0,6300000.0,5.0,5,Garut
3,2,700.0,6.300000e+06,1000000.0,1.000000e+06,300000.0,6300000.0,5.0,5,Garut
4,3,1000.0,1.000000e+07,3200000.0,5.035347e+06,1200000.0,7040000.0,5.0,5,Garut
5,4,900.0,9.000000e+06,1100000.0,6.400000e+06,180000.0,7920000.0,20.0,10,Garut
6,5,900.0,7.470000e+06,1500000.0,2.400000e+06,300000.0,8100000.0,5.0,5,Garut
...,...,...,...,...,...,...,...,...,...,...
113,25,10000.0,8.300000e+07,1000000.0,1.007069e+06,600000.0,88000000.0,20.0,15,Tasikmalaya
114,26,10000.0,8.300000e+07,1000000.0,5.000000e+06,1000000.0,88000000.0,40.0,40,Tasikmalaya
115,27,10000.0,8.300000e+07,2000000.0,1.100000e+06,280000.0,88000000.0,12.0,15,Tasikmalaya
116,28,10000.0,8.300000e+07,2000000.0,2.400000e+06,200000.0,98000000.0,10.0,13,Tasikmalaya
117,29,40000.0,3.320015e+08,3200000.0,6.000000e+06,6500000.0,350240000.0,45.0,30,Tasikmalaya

In [336]:
for loc in locations:
  print(loc)
  display(middlemen[middlemen.Location == loc].tail())

Garut

,dmu,Total rice purchase (kg),Total rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Total precipitation (%),Precipitation quality (%),Location
21,20,10000.0,83000000.0,3200000.0,2.100000e+06,1500000.0,88000000.0,0.0,0,Garut
22,21,10000.0,83000000.0,3200000.0,6.000000e+05,100000.0,88000000.0,5.0,5,Garut
23,22,10000.0,83000000.0,1000000.0,1.800000e+06,8000000.0,88000000.0,5.0,5,Garut
24,23,10000.0,83000000.0,3200000.0,5.035347e+06,1500000.0,88000000.0,5.0,5,Garut
25,24,10000.0,83000000.0,3200000.0,5.000000e+05,50000.0,88000000.0,5.0,5,Garut

Indramayu

,dmu,Total rice purchase (kg),Total rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Total precipitation (%),Precipitation quality (%),Location
40,12,14000.0,77000000.0,3200000.0,5000000.0,500000.0,1.035000e+08,0.0,0,Indramayu
41,13,20000.0,106000000.0,3200000.0,4800000.0,5000000.0,1.760000e+08,0.0,0,Indramayu
42,14,20000.0,120000000.0,3200000.0,8800000.0,10000000.0,1.900000e+08,0.0,0,Indramayu
43,15,50000.0,270000000.0,3200000.0,6000000.0,1500000.0,4.400000e+08,0.0,0,Indramayu
44,16,120000.0,960000000.0,3200000.0,8400000.0,1500000.0,1.056000e+09,0.0,0,Indramayu

Karawang

,dmu,Total rice purchase (kg),Total rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Total precipitation (%),Precipitation quality (%),Location
57,10,10000.0,70000000.0,3200000.0,8750000.0,1500000.0,88000000.0,20.0,20,Karawang
58,11,1500.0,24500000.0,1500000.0,1800000.0,1200000.0,14700000.0,0.0,0,Karawang
59,12,10000.0,83000000.0,3200000.0,5000000.0,1300000.0,88000000.0,20.0,20,Karawang
60,13,2000.0,19600000.0,1900000.0,1800000.0,1000000.0,19600000.0,20.0,20,Karawang
61,14,10000.0,75000000.0,3200000.0,5000000.0,300000.0,88000000.0,20.0,40,Karawang

Subang

,dmu,Total rice purchase (kg),Total rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Total precipitation (%),Precipitation quality (%),Location
81,17,30000.0,210000000.0,3200000.0,6000000.0,700000.0,238400000.0,50.0,50,Subang
82,18,31500.0,261450000.0,1200000.0,10000000.0,8000000.0,277200000.0,50.0,50,Subang
83,19,30000.0,150000000.0,3200000.0,10500000.0,1000000.0,283100000.0,35.0,35,Subang
84,20,35000.0,245000000.0,3200000.0,12000000.0,800000.0,313200000.0,40.0,40,Subang
85,21,50000.0,250000000.0,3200000.0,12500000.0,1500000.0,448200000.0,40.0,40,Subang

Tasikmalaya

,dmu,Total rice purchase (kg),Total rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Total precipitation (%),Precipitation quality (%),Location
113,25,10000.0,8.300000e+07,1000000.0,1.007069e+06,600000.0,88000000.0,20.0,15,Tasikmalaya
114,26,10000.0,8.300000e+07,1000000.0,5.000000e+06,1000000.0,88000000.0,40.0,40,Tasikmalaya
115,27,10000.0,8.300000e+07,2000000.0,1.100000e+06,280000.0,88000000.0,12.0,15,Tasikmalaya
116,28,10000.0,8.300000e+07,2000000.0,2.400000e+06,200000.0,98000000.0,10.0,13,Tasikmalaya
117,29,40000.0,3.320015e+08,3200000.0,6.000000e+06,6500000.0,350240000.0,45.0,30,Tasikmalaya

# Wholesaler

In [337]:
wholesaler = pd.read_excel('dataset.xlsx', engine='openpyxl', sheet_name='Wholesaler Data', header=None)
wholesaler

,0,1,2,3,4,5,6
0,Garut,NaN,NaN,NaN,NaN,NaN,NaN
1,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Precipitation quality (%),Value of rice sold (IDR)
2,1,80000000,32500000,4500000,1000000,5,100000000
3,2,9000000,10000000,600000,600000,5,9000000
4,3,9000000,10000000,600000,600000,5,9000000
...,...,...,...,...,...,...,...
113,NaN,215000000.0,2500000,8100000,6000000,25,225000000
114,NaN,270000000,4000000,6370000,2000000,20,240000000
115,NaN,380000000,2000000,11200000,5000000,20,292500000
116,NaN,37200000,2000000,8000000,1600000,50,19800000
117,NaN,96000000,4000000,16000000,5000000,30,99000000

In [338]:
wholesaler.columns = wholesaler.iloc[1].values
wholesaler

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Precipitation quality (%),Value of rice sold (IDR)
0,Garut,NaN,NaN,NaN,NaN,NaN,NaN
1,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Precipitation quality (%),Value of rice sold (IDR)
2,1,80000000,32500000,4500000,1000000,5,100000000
3,2,9000000,10000000,600000,600000,5,9000000
4,3,9000000,10000000,600000,600000,5,9000000
...,...,...,...,...,...,...,...
113,NaN,215000000.0,2500000,8100000,6000000,25,225000000
114,NaN,270000000,4000000,6370000,2000000,20,240000000
115,NaN,380000000,2000000,11200000,5000000,20,292500000
116,NaN,37200000,2000000,8000000,1600000,50,19800000
117,NaN,96000000,4000000,16000000,5000000,30,99000000

In [339]:
wholesaler.loc[90:117, 'dmu'] = range(1, len(wholesaler.loc[90:117]) + 1)
wholesaler[wholesaler.index >= 88]

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Precipitation quality (%),Value of rice sold (IDR)
88,Tasikmalaya,NaN,NaN,NaN,NaN,NaN,NaN
89,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Precipitation quality (%),Value of rice sold (IDR)
90,1,28000000,4000000,4800000,350000,10,30240000
91,2,147000000,2500000,12000000,1500000,5,169500000
92,3,192000000,4000000,17000000,25000000,20,192000000
93,4,47040000,4000000,4500000,450000,5,53280000
94,5,27440000,4000000,3600000,800000,10,31360000
95,6,529200000,4000000,8000000,10000000,20,535500000
96,7,31360000,2000000,1950000,500000,15,34720000
97,8,322000000,4000000,1500000,2100000,40,462000000
98,9,136500000,4000000,13500000,1200000,20,134400000
99,10,2816000000,8000000,40560000,80000000,20,5040000000
100,11,27440000,3000000,8400000,750000,10,31970000
101,12,114000000,4000000,29120000,32000000,20,1504000000
102,13,114000000,4000000,29000000,32000000,15,2016000000
103,14,114000000,4000000,12600000,4000000,20,600000000
104,15,114000000,3500000,8000000,4000000,25,135800000
105,16,114000000,4000000,20800000,4000000,20,440000000
106,17,114000000,4000000,20800000,4000000,20,480000000
107,18,114000000,4000000,8000000,7000000,20,500000000
108,19,114000000,4000000,8000000,16000000,15,840000000
109,20,114000000,4000000,27000000,8400000,20,968000000
110,21,114000000,4000000,31500000,24000000,15,1200000000
111,22,651000000,5000000,8000000,15000000,20,696000000.0
112,23,184000000,3000000,12000000,2000000,50,144000000
113,24,215000000.0,2500000,8100000,6000000,25,225000000
114,25,270000000,4000000,6370000,2000000,20,240000000
115,26,380000000,2000000,11200000,5000000,20,292500000
116,27,37200000,2000000,8000000,1600000,50,19800000
117,28,96000000,4000000,16000000,5000000,30,99000000

In [340]:
wholesaler.dropna(subset=['dmu'], inplace=True)
wholesaler.columns = wholesaler.iloc[1].values
wholesaler = wholesaler[~wholesaler['dmu'].isin(locations)]
wholesaler = wholesaler[wholesaler['dmu'] != 'dmu']
wholesaler['dmu'] = wholesaler['dmu'].astype(np.int64)
for col in wholesaler.columns[1:7]:
    wholesaler[col] = wholesaler[col].astype(np.float64)
wholesaler

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Precipitation quality (%),Value of rice sold (IDR)
2,1,80000000.0,32500000.0,4500000.0,1000000.0,5.0,100000000.0
3,2,9000000.0,10000000.0,600000.0,600000.0,5.0,9000000.0
4,3,9000000.0,10000000.0,600000.0,600000.0,5.0,9000000.0
5,4,16000000.0,10000000.0,1000000.0,7000000.0,5.0,16000000.0
6,5,114000000.0,4000000.0,8000000.0,2000000.0,0.0,27500000.0
...,...,...,...,...,...,...,...
113,24,215000000.0,2500000.0,8100000.0,6000000.0,25.0,225000000.0
114,25,270000000.0,4000000.0,6370000.0,2000000.0,20.0,240000000.0
115,26,380000000.0,2000000.0,11200000.0,5000000.0,20.0,292500000.0
116,27,37200000.0,2000000.0,8000000.0,1600000.0,50.0,19800000.0
117,28,96000000.0,4000000.0,16000000.0,5000000.0,30.0,99000000.0

In [341]:
locations_val = locations
location_map = []
location_idx = 0
first_row = True

for idx, row in wholesaler.iterrows():
    if int(row['dmu']) == 1 and not first_row:
        location_idx += 1
    
    first_row = False
    
    if location_idx < len(locations_val):
        location_map.append(locations_val[location_idx])
    else:
        location_map.append(None)

wholesaler['Location'] = location_map
wholesaler

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Precipitation quality (%),Value of rice sold (IDR),Location
2,1,80000000.0,32500000.0,4500000.0,1000000.0,5.0,100000000.0,Garut
3,2,9000000.0,10000000.0,600000.0,600000.0,5.0,9000000.0,Garut
4,3,9000000.0,10000000.0,600000.0,600000.0,5.0,9000000.0,Garut
5,4,16000000.0,10000000.0,1000000.0,7000000.0,5.0,16000000.0,Garut
6,5,114000000.0,4000000.0,8000000.0,2000000.0,0.0,27500000.0,Garut
...,...,...,...,...,...,...,...,...
113,24,215000000.0,2500000.0,8100000.0,6000000.0,25.0,225000000.0,Tasikmalaya
114,25,270000000.0,4000000.0,6370000.0,2000000.0,20.0,240000000.0,Tasikmalaya
115,26,380000000.0,2000000.0,11200000.0,5000000.0,20.0,292500000.0,Tasikmalaya
116,27,37200000.0,2000000.0,8000000.0,1600000.0,50.0,19800000.0,Tasikmalaya
117,28,96000000.0,4000000.0,16000000.0,5000000.0,30.0,99000000.0,Tasikmalaya

In [342]:
for loc in locations:
  print(loc)
  display(wholesaler[wholesaler.Location == loc].tail())

Garut

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Precipitation quality (%),Value of rice sold (IDR),Location
22,21,45000000.0,4000000.0,8000000.0,2000000.0,0.0,49500000.0,Garut
23,22,80000000.0,4000000.0,8000000.0,3000000.0,5.0,88000000.0,Garut
24,23,45000000.0,4000000.0,8000000.0,1350000.0,10.0,49500000.0,Garut
25,24,80000000.0,4000000.0,8000000.0,1000000.0,5.0,88000000.0,Garut
26,25,114000000.0,4000000.0,8000000.0,2000000.0,1.0,36000000.0,Garut

Indramayu

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Precipitation quality (%),Value of rice sold (IDR),Location
41,12,3.240000e+09,12000000.0,5000000.0,15000000.0,0.0,3.960000e+09,Indramayu
42,13,1.140000e+08,4000000.0,8000000.0,5000000.0,0.0,5.292000e+09,Indramayu
43,14,6.480000e+09,36000000.0,8000000.0,15000000.0,0.0,8.200000e+09,Indramayu
44,15,8.000000e+09,20000000.0,17000000.0,175000000.0,10.0,1.050000e+10,Indramayu
45,16,1.140000e+08,4000000.0,10000000.0,3000000.0,0.0,2.250000e+08,Indramayu

Karawang

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Precipitation quality (%),Value of rice sold (IDR),Location
58,10,285000000.0,4000000.0,2400000.0,5000000.0,0.0,291000000.0,Karawang
59,11,186000000.0,4000000.0,8000000.0,3000000.0,0.0,190000000.0,Karawang
60,12,90000000.0,4000000.0,8000000.0,1500000.0,40.0,144000000.0,Karawang
61,13,95000000.0,4000000.0,8000000.0,800000.0,0.0,100000000.0,Karawang
62,14,712500000.0,10000000.0,2000000.0,6000000.0,10.0,180000000.0,Karawang

Subang

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Precipitation quality (%),Value of rice sold (IDR),Location
82,17,114000000.0,4000000.0,8000000.0,3000000.0,5.0,180000000.0,Subang
83,18,114000000.0,2500000.0,1000000.0,2000000.0,5.0,300000000.0,Subang
84,19,140000000.0,5000000.0,1400000.0,1500000.0,50.0,405000000.0,Subang
85,20,135000000.0,8000000.0,3000000.0,2000000.0,50.0,540000000.0,Subang
86,21,17000000.0,3600000.0,2000000.0,500000.0,35.0,49185000.0,Subang

Tasikmalaya

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Precipitation quality (%),Value of rice sold (IDR),Location
113,24,215000000.0,2500000.0,8100000.0,6000000.0,25.0,225000000.0,Tasikmalaya
114,25,270000000.0,4000000.0,6370000.0,2000000.0,20.0,240000000.0,Tasikmalaya
115,26,380000000.0,2000000.0,11200000.0,5000000.0,20.0,292500000.0,Tasikmalaya
116,27,37200000.0,2000000.0,8000000.0,1600000.0,50.0,19800000.0,Tasikmalaya
117,28,96000000.0,4000000.0,16000000.0,5000000.0,30.0,99000000.0,Tasikmalaya

# Retail

In [343]:
retail = pd.read_excel('dataset.xlsx', engine='openpyxl', sheet_name='Retail Data', header=None)
retail.dropna(subset=[0], inplace=True)
retail = retail.iloc[:, :6]
retail.columns = retail.iloc[1].values
retail = retail[~retail['dmu'].isin(locations)]
retail = retail[retail['dmu'] != 'dmu']
retail['dmu'] = retail['dmu'].astype(np.int64)
for col in retail.columns[1:6]:
    retail[col] = retail[col].astype(np.float64)
retail
retail

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR)
2,1,1375000.0,200000.0,3000000.0,150000.0,1750000.0
3,2,2700000.0,200000.0,3000000.0,200000.0,3500000.0
4,3,2700000.0,200000.0,3000000.0,200000.0,3500000.0
5,4,2695000.0,200000.0,3000000.0,30000.0,3000000.0
6,5,2612500.0,200000.0,3000000.0,300000.0,3500000.0
...,...,...,...,...,...,...
112,24,2695000.0,200000.0,3000000.0,150000.0,3520000.0
113,25,2450000.0,150000.0,3000000.0,200000.0,2000000.0
114,26,2850000.0,200000.0,400000.0,200000.0,2250000.0
115,27,2250000.0,200000.0,2000000.0,500000.0,3000000.0
116,28,2695000.0,250000.0,2000000.0,300000.0,2500000.0

In [344]:
locations_val = locations
location_map = []
location_idx = 0
first_row = True

for idx, row in retail.iterrows():
    if int(row['dmu']) == 1 and not first_row:
        location_idx += 1
    
    first_row = False
    
    if location_idx < len(locations_val):
        location_map.append(locations_val[location_idx])
    else:
        location_map.append(None)

retail['Location'] = location_map
retail

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Location
2,1,1375000.0,200000.0,3000000.0,150000.0,1750000.0,Garut
3,2,2700000.0,200000.0,3000000.0,200000.0,3500000.0,Garut
4,3,2700000.0,200000.0,3000000.0,200000.0,3500000.0,Garut
5,4,2695000.0,200000.0,3000000.0,30000.0,3000000.0,Garut
6,5,2612500.0,200000.0,3000000.0,300000.0,3500000.0,Garut
...,...,...,...,...,...,...,...
112,24,2695000.0,200000.0,3000000.0,150000.0,3520000.0,Tasikmalaya
113,25,2450000.0,150000.0,3000000.0,200000.0,2000000.0,Tasikmalaya
114,26,2850000.0,200000.0,400000.0,200000.0,2250000.0,Tasikmalaya
115,27,2250000.0,200000.0,2000000.0,500000.0,3000000.0,Tasikmalaya
116,28,2695000.0,250000.0,2000000.0,300000.0,2500000.0,Tasikmalaya

In [345]:
for loc in locations:
  print(loc)
  display(retail[retail.Location == loc].tail())

Garut

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Location
20,19,2695000.0,100000.0,1000000.0,150000.0,3000000.0,Garut
21,20,1900000.0,200000.0,3000000.0,300000.0,3500000.0,Garut
22,21,2695000.0,100000.0,3500000.0,300000.0,3000000.0,Garut
23,22,2700000.0,100000.0,3500000.0,300000.0,3600000.0,Garut
24,23,2612500.0,200000.0,3000000.0,100000.0,3500000.0,Garut

Indramayu

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Location
39,12,2695000.0,200000.0,4500000.0,400000.0,3500000.0,Indramayu
40,13,2695000.0,100000.0,4000000.0,200000.0,3600000.0,Indramayu
41,14,2475000.0,250000.0,2000000.0,400000.0,3000000.0,Indramayu
42,15,2695000.0,200000.0,3000000.0,200000.0,3500000.0,Indramayu
43,16,1900000.0,200000.0,4000000.0,200000.0,3000000.0,Indramayu

Karawang

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Location
58,12,1800000.0,250000.0,3000000.0,300000.0,3000000.0,Karawang
59,13,2695000.0,200000.0,3000000.0,200000.0,3000000.0,Karawang
60,14,2695000.0,200000.0,3000000.0,150000.0,3000000.0,Karawang
61,15,2695000.0,100000.0,3000000.0,50000.0,3000000.0,Karawang
62,16,1960000.0,100000.0,3000000.0,200000.0,3000000.0,Karawang

Subang

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Location
81,15,2695000.0,200000.0,1000000.0,100000.0,3000000.0,Subang
82,16,2250000.0,200000.0,3000000.0,50000.0,3000000.0,Subang
83,17,1750000.0,200000.0,3000000.0,50000.0,2000000.0,Subang
84,18,1400000.0,200000.0,3000000.0,50000.0,1800000.0,Subang
85,19,1750000.0,200000.0,3000000.0,50000.0,1600000.0,Subang

Tasikmalaya

,dmu,Value of rice purchase (IDR),Building rent cost (IDR),Labor cost (IDR),Supporting equipment cost (IDR),Value of rice sold (IDR),Location
112,24,2695000.0,200000.0,3000000.0,150000.0,3520000.0,Tasikmalaya
113,25,2450000.0,150000.0,3000000.0,200000.0,2000000.0,Tasikmalaya
114,26,2850000.0,200000.0,400000.0,200000.0,2250000.0,Tasikmalaya
115,27,2250000.0,200000.0,2000000.0,500000.0,3000000.0,Tasikmalaya
116,28,2695000.0,250000.0,2000000.0,300000.0,2500000.0,Tasikmalaya

# Exporting Data

In [346]:
farmer.to_csv('farmer.csv', index=False)
rice_miller.to_csv('rice_miller.csv', index=False)
middlemen.to_csv('middlemen.csv', index=False)
wholesaler.to_csv('wholesaler.csv', index=False)
retail.to_csv('retail.csv', index=False)